# Generated by Django 5.0.7 on 2024-07-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=40),
        ),
    ]
