# Generated by Django 5.0.7 on 2024-07-21 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('liked_posts', models.ManyToManyField(blank=True, related_name='liked_by', to='post.post')),
            ],
        ),
    ]
